server:
  port: 0

spring:
  application:
    name: character-service

security:
  oauth2:
    resource:
      user-info-uri: https://dev-826281.oktapreview.com/oauth2/default/v1/userinfo
      prefer-token-info: false

feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true
