server:
  port: 8081
spring:
  application:
    name: edge-service

zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    account:
      service-id: account-service
      path: /account
    character:
      service-id: character-service
      path: /character
    test:
      service-id: character-service
      path: /test
    token:
      service-id: account-service
      path: /token

security:
  oauth2:
    resource:
      user-info-uri: https://dev-826281.oktapreview.com/oauth2/default/v1/userinfo
    client:
      client-id: 0oaj8lccdv5KFZwnZ0h7
      client-secret: HRFcdTgo2JJvueNwBqzkkSAKfT4WL41IPWF_Mfv7
      access-token-uri: https://dev-826281.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-826281.oktapreview.com/oauth2/default/v1/authorize
      scope: openid profile email



