server:
  port: 0

spring:
  application:
    name: account-service

security:
  oauth2:
    resource:
      user-info-uri: https://dev-826281.oktapreview.com/oauth2/default/v1/userinfo
    client:
      client-id: 0oaj8lccdv5KFZwnZ0h7
      client-secret: HRFcdTgo2JJvueNwBqzkkSAKfT4WL41IPWF_Mfv7
      access-token-uri: https://dev-826281.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-826281.oktapreview.com/oauth2/default/v1/authorize
      scope: openid profile email

management:
  endpoints:
    web:
      exposure:
        include: beans,mappings